import React from 'react';

export default function Success() {
  const reviews = [
    {
      name: 'Dr. Olivia W.',
      role: 'Founder, Aether Clinique (Beverly Hills)',
      rating: 5,
      date: 'Google Review — 1 month ago',
      text: 'We were completely buried on maps search in Beverly Hills. Aura & Rank optimized our listing and re-built our booking pages. Within 60 days, our patient inquiries rate surged and we gathered over 120 fresh 5-star reviews. It changed our practice completely.',
      keyword: 'Ranked #1 for Dermatology'
    },
    {
      name: 'Marcus Sterling',
      role: 'Director, Vanguard Realty Group (Miami)',
      rating: 5,
      date: 'Google Review — 3 months ago',
      text: 'The return on investment was immediate. Their ads campaign for our new luxury properties booked us out weeks in advance. The web canvas looks incredibly premium and is extremely fast. Highly recommend to any high-end business leader.',
      keyword: '4.8x ROI on Meta Ads'
    },
    {
      name: 'Victoria Mercer',
      role: 'Owner, Mercer Soho (New York City)',
      rating: 5,
      date: 'Google Review — 2 weeks ago',
      text: 'Working with them has been effortless. Our local search impressions rose by over 300,000 in the first quarter alone. Our reservations are full and we no longer need to run discounts or cheap promotions to attract new guests.',
      keyword: '3.2x Reservations Growth'
    },
    {
      name: 'Elena Rostova',
      role: 'Owner, Elysian Salon & Spa (Manhattan)',
      rating: 5,
      date: 'Google Review — 2 months ago',
      text: 'Their automated review generation system works like magic. It pulls 5-star ratings from our clients automatically after they check out. Our map rank climbed from #18 to the top 3 in Manhattan.',
      keyword: '+380 Google Reviews Generated'
    }
  ];

  return (
    <div style={styles.container}>
      {/* HEADER SECTION */}
      <section style={styles.header}>
        <p style={styles.tag}>THE COHORT</p>
        <h1 style={styles.title}>Client Success</h1>
        <p style={styles.sub}>
          Real industry leaders. Documented scale. Discover the revenue and review impact generated by our local search and conversion design systems.
        </p>
      </section>

      {/* TRUST METRICS BLOCK */}
      <section style={styles.statsGrid}>
        <div className="glass-panel" style={styles.statCard}>
          <h3 style={styles.statVal}>+3,800</h3>
          <p style={styles.statLabel}>Reviews Generated</p>
          <p style={styles.statSub}>Fully automated post-visit feedback loops</p>
        </div>

        <div className="glass-panel" style={styles.statCard}>
          <h3 style={styles.statVal}>12M+</h3>
          <p style={styles.statLabel}>Local Search Impressions</p>
          <p style={styles.statSub}>Aggregated organic maps exposure</p>
        </div>

        <div className="glass-panel" style={styles.statCard}>
          <h3 style={styles.statVal}>60+</h3>
          <p style={styles.statLabel}>Luxury Websites Built</p>
          <p style={styles.statSub}>Bespoke high-converting scheduling canvases</p>
        </div>
      </section>

      {/* CINEMATIC VIDEO SPOTLIGHT */}
      <section style={styles.videoSection}>
        <div style={styles.videoHeader}>
          <p style={styles.tag}>SPOTLIGHT</p>
          <h2 style={styles.videoTitle}>Dr. Olivia W. on scaling Aether Clinique</h2>
        </div>

        <div className="glass-panel" style={styles.videoBox}>
          {/* Abstract representation of a premium video player */}
          <div style={styles.videoOverlay}>
            <div style={styles.playButton}>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" style={{ marginLeft: '4px' }}>
                <polygon points="5,3 19,12 5,21" />
              </svg>
            </div>
            <div style={styles.videoDetails}>
              <h4 style={styles.videoCaption}>"We filled our calendar and stopped running discounts."</h4>
              <p style={styles.videoSubText}>Aether Clinique case study — 4:12 mins</p>
            </div>
          </div>
        </div>
      </section>

      {/* REVIEWS DIRECTORY */}
      <section style={styles.reviewsSection}>
        <div style={styles.reviewsHeader}>
          <p style={styles.tag}>VERIFIED RATINGS</p>
          <h2 style={styles.reviewsTitle}>Google Review Ledger</h2>
        </div>

        <div style={styles.grid}>
          {reviews.map((rev, idx) => (
            <div key={idx} className="glass-card" style={styles.card}>
              <div style={styles.cardHeader}>
                <div>
                  <h4 style={styles.cardName}>{rev.name}</h4>
                  <p style={styles.cardRole}>{rev.role}</p>
                </div>
                <div style={styles.googleIcon}>
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12.24 10.285V14.4h6.887c-.648 2.41-2.519 4.114-5.136 4.114A5.99 5.99 0 018 12.5a5.99 5.99 0 015.991-6.014c1.554 0 2.973.57 4.07 1.612l3.078-3.078C19.261 3.167 16.782 2 13.991 2 8.164 2 3.5 6.664 3.5 12.5S8.164 23 13.991 23c5.622 0 10.129-4.06 10.129-10.285 0-.584-.05-1.168-.148-1.715H12.24v-.715z" />
                  </svg>
                </div>
              </div>

              <div style={styles.stars}>
                {'★'.repeat(rev.rating)}
              </div>

              <p style={styles.cardText}>"{rev.text}"</p>

              <div style={styles.cardFooter}>
                <span style={styles.cardDate}>{rev.date}</span>
                <span style={styles.cardTag}>{rev.keyword}</span>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

const styles = {
  container: {
    padding: '0 3rem',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  header: {
    padding: '5rem 0',
    textAlign: 'center',
  },
  tag: {
    fontFamily: 'var(--font-sans)',
    fontSize: '0.75rem',
    fontWeight: '700',
    letterSpacing: '0.25em',
    color: 'var(--gold-base)',
    marginBottom: '1rem',
  },
  title: {
    fontSize: '4.25rem',
    lineHeight: '1.15',
    marginBottom: '1.5rem',
  },
  sub: {
    fontSize: '1.2rem',
    color: 'var(--text-muted)',
    maxWidth: '650px',
    margin: '0 auto',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '2rem',
    margin: '1rem 0 6rem 0',
  },
  statCard: {
    padding: '3rem 2rem',
    textAlign: 'center',
    borderRadius: 'var(--border-radius-md)',
  },
  statVal: {
    fontFamily: 'var(--font-serif)',
    fontSize: '3.5rem',
    fontStyle: 'italic',
    color: 'var(--gold-base)',
    fontWeight: '700',
    marginBottom: '0.5rem',
  },
  statLabel: {
    fontSize: '1rem',
    fontWeight: '600',
    color: 'var(--text-primary)',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    marginBottom: '0.5rem',
  },
  statSub: {
    fontSize: '0.82rem',
    color: 'var(--text-muted)',
  },
  videoSection: {
    padding: '4rem 0 6rem 0',
    borderTop: '1px solid var(--border-color)',
  },
  videoHeader: {
    textAlign: 'center',
    marginBottom: '3rem',
  },
  videoTitle: {
    fontSize: '2.5rem',
    marginTop: '0.5rem',
  },
  videoBox: {
    height: '460px',
    borderRadius: 'var(--border-radius-lg)',
    overflow: 'hidden',
    position: 'relative',
    background: 'linear-gradient(135deg, #18181b 0%, #0a0a0b 100%)',
    backgroundImage: 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'100\' height=\'100\' viewBox=\'0 0 100 100\'%3E%3Crect width=\'100\' height=\'100\' fill=\'none\'/%3E%3Ccircle cx=\'50\' cy=\'50\' r=\'1\' fill=\'rgba(212,180,110,0.06)\'/%3E%3C/svg%3E")',
    backgroundSize: '30px 30px',
    boxShadow: '0 30px 60px rgba(0,0,0,0.5)',
  },
  videoOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'radial-gradient(circle, rgba(10,10,11,0.4) 0%, rgba(10,10,11,0.85) 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '2rem',
    cursor: 'pointer',
    transition: 'var(--transition-smooth)',
  },
  playButton: {
    width: '74px',
    height: '74px',
    borderRadius: '50%',
    backgroundColor: 'var(--gold-base)',
    color: 'var(--bg-primary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    boxShadow: '0 0 30px rgba(212,180,110,0.3)',
    marginBottom: '2rem',
    transition: 'var(--transition-smooth)',
  },
  videoDetails: {
    textAlign: 'center',
  },
  videoCaption: {
    fontFamily: 'var(--font-serif)',
    fontSize: '1.85rem',
    fontStyle: 'italic',
    color: 'var(--text-primary)',
    marginBottom: '0.5rem',
  },
  videoSubText: {
    fontSize: '0.85rem',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  reviewsSection: {
    padding: '4rem 0 8rem 0',
    borderTop: '1px solid var(--border-color)',
  },
  reviewsHeader: {
    textAlign: 'center',
    marginBottom: '4rem',
  },
  reviewsTitle: {
    fontSize: '3.25rem',
    lineHeight: '1.2',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '2.5rem',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
    justifyContent: 'space-between',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  cardName: {
    fontSize: '1.35rem',
    fontWeight: '600',
    color: 'var(--text-primary)',
  },
  cardRole: {
    fontSize: '0.82rem',
    color: 'var(--text-muted)',
    marginTop: '0.2rem',
  },
  googleIcon: {
    color: 'rgba(255,255,255,0.15)',
  },
  stars: {
    color: 'var(--gold-base)',
    letterSpacing: '2px',
    fontSize: '0.95rem',
  },
  cardText: {
    fontSize: '0.98rem',
    color: 'var(--text-secondary)',
    lineHeight: '1.6',
    fontStyle: 'italic',
  },
  cardFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '0.5rem',
    borderTop: '1px solid rgba(255,255,255,0.02)',
    paddingTop: '1rem',
  },
  cardDate: {
    fontSize: '0.78rem',
    color: 'var(--text-muted)',
  },
  cardTag: {
    fontSize: '0.78rem',
    color: 'var(--gold-base)',
    fontWeight: '600',
  },
};
